#Git command aliases
alias ad="git add"
alias cm="git commit -m"
alias ch="git checkout"
alias gs="git status"
alias pu="git push"
alias pur="git push --upstream"
alias fetch="git fetch"
alias br="git branch"
alias pul="git pull"
